### ISSUE TITLE
First login time is a success... then fails

### ISSUE THREAD

**Issue by DaLynxx** [saltcorn/ldap-auth#1]
When I run with the proposed test settings, i.e. against the forumsys.com the first login with the euler / password is a success.

There is a user created.

However, if I logout and then try to login again. I always get "Unauthorized".

If I delete the created eule@ldap.forumsys.com user. It will work once more.

When googling some I found the following forum post which seems to have the same problem. https://forum.saltcorn.com/view/ShowThread?id=40

**Comment by RogueSnipa** [comment]
+1. I have same problem on saltcorn version 0.8.2
